name: logsage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/sounds/alarm.wav
  uses-material-design: true
